#' Connect to PostgreSQL Database
#'
#' Establishes a connection to the Postgres database used by the web app and ingestion job.
#'
#' @param db_path Kept for backwards-compatible callers; DATABASE_URL is used when set.
#' @return A DBI connection object.
#' @importFrom DBI dbConnect
#' @importFrom RPostgres Postgres
#' @export
postgres_connect_url <- function(database_url) {
    parsed <- httr2::url_parse(database_url)
    if (!parsed$scheme %in% c("postgres", "postgresql") || is.null(parsed$hostname)) {
        stop("DATABASE_URL must be a PostgreSQL URL.")
    }

    args <- list(
        drv = RPostgres::Postgres(),
        dbname = sub("^/", "", parsed$path),
        host = parsed$hostname,
        port = as.integer(parsed$port %||% "5432"),
        user = parsed$username %||% "",
        password = parsed$password %||% ""
    )
    if (!is.null(parsed$query$sslmode)) {
        args$sslmode <- parsed$query$sslmode
    }

    do.call(DBI::dbConnect, args)
}

`%||%` <- function(value, fallback) {
    if (is.null(value) || length(value) == 0 || identical(value, "")) fallback else value
}

require_database_url <- function(fallback = "") {
    database_url <- Sys.getenv("DATABASE_URL", unset = fallback)
    if (database_url == "") {
        stop("DATABASE_URL is required.")
    }
    database_url
}

database_target_label <- function(database_url = require_database_url()) {
    parsed <- httr2::url_parse(database_url)
    paste0(
        parsed$hostname,
        ":",
        parsed$port %||% "5432",
        "/",
        sub("^/", "", parsed$path)
    )
}

get_db_connection <- function(db_path = "") {
    database_url <- require_database_url(db_path)
    con <- NULL
    for (i in 1:60) {
        tryCatch({
            con <- postgres_connect_url(database_url)
            break
        }, error = function(e) {
            if (grepl("connection|could not|timeout|refused|starting", tolower(e$message))) {
                if (i == 60) stop("Database unavailable for too long: ", e$message)
                message("Database unavailable (attempt ", i, "/60). Retrying in 1 second...")
                Sys.sleep(1)
            } else {
                stop("Database connection failed: ", e$message)
            }
        })
    }
    
    DBI::dbExecute(con, "SET search_path TO corpus, public;")
    
    return(con)
}

#' Initialize Database Tables and Schemas
#'
#' Sets up the schema for newsletters, entities, and the entity lexicon lookup.
#'
#' @param con A DBI database connection.
#' @export
init_db <- function(con) {
    DBI::dbExecute(con, "CREATE EXTENSION IF NOT EXISTS vector;")
    DBI::dbExecute(con, "CREATE SCHEMA IF NOT EXISTS corpus;")
    DBI::dbExecute(con, "SET search_path TO corpus, public;")

    # 1. Create newsletters table
    DBI::dbExecute(con, "
        CREATE TABLE IF NOT EXISTS newsletters (
            uid VARCHAR PRIMARY KEY,
            datetime TIMESTAMP,
            source VARCHAR,
            sender VARCHAR,
            title VARCHAR,
            url VARCHAR,
            summary TEXT,
            original_language_summary TEXT,
            detected_language VARCHAR,
            truncated BOOLEAN,
            content_type VARCHAR,
            topics TEXT,
            themes TEXT,
            keywords TEXT,
            subscription_marketing BOOLEAN,
            english_embedding vector,
            multilingual_embedding vector,
            flag_status TEXT DEFAULT NULL,
            raw_email TEXT,
            ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ")
    
    DBI::dbExecute(con, "ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS url VARCHAR;")
    DBI::dbExecute(con, "ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS flag_status TEXT DEFAULT NULL;")
    DBI::dbExecute(con, "ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS raw_email TEXT;")
    
    # 2. Create entity ID sequence and entities table
    DBI::dbExecute(con, "
        CREATE TABLE IF NOT EXISTS entities (
            entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            uid VARCHAR REFERENCES newsletters(uid) ON DELETE CASCADE,
            entity_type VARCHAR,
            raw_name VARCHAR,
            canonical_name VARCHAR
        );
    ")
    
    # 3. Create entity lexicon table for deduplication
    DBI::dbExecute(con, "
        CREATE TABLE IF NOT EXISTS entity_lexicon (
            raw_name VARCHAR PRIMARY KEY,
            canonical_name VARCHAR,
            entity_type VARCHAR,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ")

    DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS newsletters_datetime_idx ON newsletters (datetime DESC);")
    DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS newsletters_content_type_idx ON newsletters (content_type);")
    DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS newsletters_language_idx ON newsletters (detected_language);")
    DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS entities_uid_idx ON entities (uid);")
    
    message("Postgres corpus tables initialized successfully.")
}

#' Close Database Connection
#'
#' Safely closes the database connection and releases memory.
#'
#' @param con A DBI database connection.
#' @export
close_db_connection <- function(con) {
    if (!is.null(con)) {
        DBI::dbDisconnect(con)
    }
}
